name: Release Tag
permissions:
    contents: read
    issues: write 
on:
  push:
    tags:
        - 'v[0-9]+'
        # git tag v15
        # git push origin v15

jobs:
  release:
    name: release on tag
    timeout-minutes: 10
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm ci
    - run: npm run build
    - run: npm test
    - run: npx playwright install
    - run: npx playwright test --project=chromium
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
    
    - name: Update CHANGELOG
      id: changelog
      uses: requarks/changelog-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref_name }}
    
    - run: cat CHANGELOG.md
    - run: ls -1
    - run: sh issue-maker.sh
      env:
        REF_NAME: ${{ github.ref_name }}
        ACTOR: ${{ github.actor }}
    - run: cat ISSUE.md
    - run: cat ISSUE.md CHANGELOG.md > .github/ISSUE_TEMPLATE.md
    - run: cat .github/ISSUE_TEMPLATE.md

    - name: Create an issue
      uses: JasonEtco/create-an-issue@v2.9.1
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-and-deploy: 
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm ci
      - run: npm run build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          branch: gh-pages