name: Page build (gh-pages)
run-name: Record build
on: 
  page_build
jobs:
  Save_build:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:

      - uses: actions/checkout@v3

      - name: Find the last open report issue
        id: last-issue
        uses: micalevisk/last-issue-action@v2
        with:
          state: open
          labels: RELEASE

      - name: Release tag
        if: ${{ steps.last-issue.outputs.has-found == 'true' }}
        uses: peter-evans/create-or-update-comment@v3.0.2
        with:
          body: 
            Build successfully completed
          issue-number: ${{ steps.last-issue.outputs.issue-number }}

      - name: Close Issue
        uses: peter-evans/close-issue@v3
        with:
          issue-number: ${{ steps.last-issue.outputs.issue-number }}
          comment: Auto-closing issue

                    
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
